server {
    server_name localhost;

     # Path to the build output
     root /usr/share/nginx/html;

     # Serve the index.html for all routes
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Serve static assets with caching
    location /assets/ {
        access_log off;
        expires 1y;
        add_header Cache-Control "public";
    }

    # Fallback to index.html for 404 errors
    error_page 404 /index.html;

}