name: Auto-Approve and Merge My PRs

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-approve-and-merge:
    if: github.actor == github.event.pull_request.user.login
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Auto-approve the PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge the PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
